[package]
name = "atcoder-problems-sql-common"
version = "0.1.0"
authors = ["kenkoooo <kenkou.n@gmail.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.4.2", features = ["postgres"] }
regex = "1"
serde = { version = "1.0", features = ["derive"] }