services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  dbt:
    build: ./dbt
    environment:
      - DBT_PROFILES_DIR=/dbt
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./dbt:/dbt
    working_dir: /dbt
    depends_on:
      - postgres
