FROM rust:1.63.0 AS development
RUN rustup component add rustfmt
RUN rustup component add clippy

# Install cargo-watch
RUN wget "https://github.com/watchexec/cargo-watch/releases/download/v8.4.0/cargo-watch-v8.4.0-$(uname -m)-unknown-linux-gnu.tar.xz" \
    && tar -xf "cargo-watch-v8.4.0-$(uname -m)-unknown-linux-gnu.tar.xz" \
    && cp "cargo-watch-v8.4.0-$(uname -m)-unknown-linux-gnu/cargo-watch" /usr/local/bin/ \
    && rm -rf "cargo-watch-v8.4.0-$(uname -m)-unknown-linux-gnu"
