[package]
name = "atcoder-problems-api-server"
version = "0.1.0"
authors = ["Kenkou Nakamura <knakamura@indeed.com>"]
edition = "2018"

[dependencies]
postgres = "0.15"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
actix-web = "0.7.18"
actix = "0.7.9"
regex = "1"
