[package]
name = "atcoder-problems-api-server"
version = "0.1.0"
authors = ["Kenkou Nakamura <knakamura@indeed.com>"]
edition = "2018"

[dependencies]
postgres = "0.15"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
url = "1.7.2"
iron = "0.6"
