name: Frontend build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  frontend-build:
    name: Build frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./atcoder-problems-frontend
        shell: bash

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8.15.9
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: ./atcoder-problems-frontend/pnpm-lock.yaml
      - uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: "0.4.40"
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - run: pnpm run lint
